### ISSUE TITLE
Attribute completeness validator

### ISSUE THREAD

**Issue by geohacker** [hotosm/osma-health#4]
For a building structure, attribute completeness is defined if it has the following tags:
* `building=residential`
* `wall=*`
* `roof` or `roof:material`

We'll build an OSMLint validator to export all buildings that doesn't have the above and build the following statistics:
* % untagged closed ways
* % building=residential - measure of incompleteness
* % of buildings=residential that are tagged with wall and roof attributes - completeness

cc @hotosm/osma-health

**Comment by kamicut** [comment]
@geohacker should we also have the `% of building=yes` that don't have a specific `building` value?

**Comment by geohacker** [comment]
@kamicut thinking about this a bit more - I think we don't want to make this part of OSMLint, but use https://github.com/mapbox/osm-tag-stats to get the stats directly for the combination of tags we want. 

@karito, let's make sure we get this right before you start working on the osmlint function

**Comment by smit1678** [comment]
👍 

@awright can you double check the tags against the Botswana data collection model? Some of the tags in the data model aren't relevant but let's double check.

**Comment by awright** [comment]
i didn't see @smit1678 message to right now, but i wanted to pass along the HOT Botswana field collection data model for reference. the 2nd section is most relevant and confirms this. i'm not sure this would change anything. let me know if you see differently. cc @geohacker 

### Data to be verified:
- Buildings that were falsely enumerated – i.e. buildings in the OSM dataset that do not exist on the ground
  - These buildings will be given a `note` with the text `NOT PRESENT` (or similar message), and will be removed from OSM
- Buildings that were missed – i.e. buildings that existed on the ground but were missed during enumeration
- Buildings that are new – so now exist, but couldn’t have been in the dataset because they didn’t exist 8 months ago
  - Data for this building will be collected as a `node` (single point), and can be tracked/upgraded to proper geometry later.

### Data to be collected per building (linked to OSM schema):
- Type/primary use of the `building` (residential, commercial, government, school, hospital, etc)
- Wall material (`building:wall`): OSM values: brick, cement_block, concrete, loam, metal, plaster, wood, plastic, mud
- Roofing  material (`building:roof`). OSM values: thatch, wood, slate, asphalt, asbestos, metal, plastic, rubber, ceramic, cement, mud.
- Data collection forms should allow capturing a `note` for other relevant info as encountered by data collectors.

### The following information will not be captured given the anticipated challenge and time to locate and interview people in their homes during implementation:
- `room` to capture number of rooms (this is an edge case; there is an OSM tag that supports this, but in general it is not suitable to store/collect information ‘behind the front door’)
- `number of household members`
